# 一个workflow，名为deploy to tengxunyun
name: deploy to tengxunyun

on: # 此CI/CD触发时的事件
  push: # 在代码提交时自动触发
    branches:
      - master

# 一个 CI/CD 的工作流有许多 jobs 组成，比如最典型的 job 是 lint，test，build。
jobs: 
  build: # 构建job
    runs-on: ubuntu-latest # 跑workflow的服务器系统
    steps: # job的一系列动作
      # 切换分支获取源码
      - name: Checkout # step的名称，将会在 github action 的控制台中显示
        # 选择一个action，可以理解为若干 steps.run，有利于代码复用
        uses: actions/checkout@master
      # 安装使用 node
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: 安装依赖
        run: yarn install --frozen-lockfile

      - name: 构建文档
        env:
          CI: true
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          yarn run docs:build
          > docs/.vuepress/dist/.nojekyll

 
